#!/bin/bash

INPUT_DIR=`jq -r '.fsin' config.json`
#OUTPUT_DIR=`jq -r '' config.json`
OUTPUT_DIR='out'
#FS_VERSION=`jq -r '.' config.json`
FS_VERSION='6p0'

mkdir -p ${PWD}/${OUTPUT_DIR}

####################################################################
####################################################################

# setup FSL & FREESURFER
module load fsl
module load freesurfer

####################################################################
####################################################################

# fetch the data
wget -q https://ndownloader.figshare.com/files/10791467
tar -vxf 10791467

####################################################################
####################################################################

export atlasBaseDir=${PWD}
export scriptBaseDir=${PWD}

# make a list from these options: 
# nspn500 gordon333 yeo17 hcp-mmp schaefer100-yeo17 
# schaefer200-yeo17 schaefer400-yeo17 schaefer600-yeo17 schaefer800-yeo17 
# schaefer1000-yeo17

export atlasList="schaefer100-yeo17 schaefer200-yeo17 yeo17"

####################################################################
####################################################################
# subject variables

#subj="my_subject"
#inputFSDir="/path/to/freesurfer/${subj}/"
#outputDir="/output/to/somwhere/${subj}/"
#mkdir -p ${outputDir}

####################################################################
####################################################################
# go into the folder where we also want output and setup notes file!

cmd="${scriptBaseDir}/src/maTT2_applyGCS.sh \
        -d ${INPUT_DIR} \
        -o ${PWD}/${OUTPUT_DIR}/ \
        -f ${FS_VERSION} \
    "
echo $cmd 
eval $cmd | tee -a ${OUT}























