#!/bin/bash

INPUT_DIR=`jq -r '.fsin' config.json`
#OUTPUT_DIR=`jq -r '' config.json`
OUTPUT_DIR='out'
#FS_VERSION=`jq -r '.' config.json`
FS_VERSION='6p0'

mkdir -p ${PWD}/${OUTPUT_DIR}

####################################################################
####################################################################

# setup FSL & FREESURFER
module load fsl
module load freesurfer

####################################################################
####################################################################

export atlasBaseDir=${PWD}
export scriptBaseDir=${PWD}

# make a list from these options: 
# nspn500 gordon333 yeo17 hcp-mmp schaefer100-yeo17 
# schaefer200-yeo17 schaefer400-yeo17 schaefer600-yeo17 schaefer800-yeo17 
# schaefer1000-yeo17

export atlasList="schaefer100-yeo17 schaefer200-yeo17 yeo17"

####################################################################
####################################################################

# fetch the data, if it does not already exist
gcsMissing=0
gcsFiles=''

for ii in ${atlasList}
do
    for hemi in lh rh
    do
        currGCS=${atlasBaseDir}/atlas_data/${ii}/${hemi}.${ii}_${FS_VERSION}.gcs
        if [[ ! -f ${currGCS} ]]
        then
	    gcsMissing=1
	    break
        fi
    done
done

if [[ ${gcsMissing} -eq 1 ]]
then
    wget -q https://ndownloader.figshare.com/files/10791467
    tar -vxf 10791467
else
    echo "gcs data already present"
fi

####################################################################
####################################################################
# subject variables

#subj="my_subject"
#inputFSDir="/path/to/freesurfer/${subj}/"
#outputDir="/output/to/somwhere/${subj}/"
#mkdir -p ${outputDir}

####################################################################
####################################################################
# go into the folder where we also want output and setup notes file!

touch ${PWD}/${OUTPUT_DIR}/log.txt

cmd="${scriptBaseDir}/src/maTT2_applyGCS.sh \
        -d ${INPUT_DIR} \
        -o ${PWD}/${OUTPUT_DIR}/ \
        -f ${FS_VERSION} \
    "
echo $cmd 
eval $cmd | tee -a ${OUT}























